version: '3'

services:
  postgres_db:
    image: postgres:16.1-alpine3.17
    container_name: postgres_db
    environment:
      POSTGRES_USER: nammtrong023
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: airbnb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - 8080:8080

volumes:
  postgres-data:
